# Cooldown time (in ticks) for enderpearls. Recommended: 300
cooldown: 300

# Refund enderpearl if the teleport is canceled by any plugin. Recommended: true
refund-canceled: true

# Cancel launch if the player is suffocating. Recommended: true
cancel-launch-suffocating: true

# Cancel pearls that land inside blocks. (Almost never happens) Recommended: true
cancel-landing-inside-block: true

# Cancel pearls that land in areas smaller than 0.6 blocks wide. Recommended: false
cancel-landing-small-area: false

# Cancel pearls that land in areas where the player would be suffocating. Recommended: false
cancel-landing-suffocating: false