# Cooldown time (in ticks) for enderpearls.  Recommended: 300
cooldown: 300

# Refund enderpearl if the teleport is canceled by any plugin. Recommended: true
refund-canceled: true

# Cancel launch if the player is suffocating. Recommended: true
cancel-launch-suffocating: true

# Cancel pearls that land inside blocks. Recommended: true
cancel-land-inside-block: true

messages:
  # Options: {TIME} - Seconds until cooldown ends.
  cancel-launch-cooldown: "&cYou cannot pearl for another &b{TIME}&r&c seconds."

  cancel-launch-suffocating: "&cYou cannot pearl while suffocating."

  cancel-land-inside: "&cYou cannot pearl inside of a block."